const ActionTypes = {
  isLogin: 'IS_LOGIN',
  showAlert: 'SHOW_ALERT',
  hideAlert: 'HIDE_ALERT',
  showLoading: 'SHOW_LOADING',
  hideLoading: 'HIDE_LOADING',
  USER_DATA: 'USER_DATA',
  LOGOUT: 'LOGOUT',

  //Teams
  GET_TEAMS: 'GET_TEAMS',
  SELECTED_TEAMS: 'SELECTED_TEAMS',
  UPDATE_TEAM: 'UPDATE_TEAM',
  MANAGE_TEAM: 'MANAGE_TEAM',
  MANAGE_TEAM_PLAYER: 'MANAGE_TEAM_PLAYER',
  REMOVE_TEAM_REQ: 'REMOVE_TEAM_REQ',
  REMOVE_PLAYER_REQ: 'REMOVE_PLAYER_REQ',
  RESET_TEAMS: 'RESET_TEAMS',

  //Players
  GET_PLAYERS: 'GET_PLAYERS',
  RESET_PLAYERS: 'RESET_PLAYERS',
  GET_LINEUP_PLAYERS: 'GET_LINEUP_PLAYERS',

  //Notifications
  GET_TYPES: 'GET_TYPES',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  RESET_NOTIFICATION: 'RESET_NOTIFICATION',

  //Dashboard
  GET_DASHBOARD: 'GET_DASHBOARD',
  RESET_DASHBOARD: 'RESET_DASHBOARD',

  //Tournament
  GET_TOURNAMENTS: 'GET_TOURNAMENTS',
  GET_TOUR_DETAIL: 'GET_TOUR_DETAIL',
  RESET_TOURNAMENT: 'RESET_TOURNAMENT',

  //Videos
  GET_VIDEOS: 'GET_VIDEOS',
  RESET_VIDEOS: 'RESET_VIDEOS',

  //Match
  MATCH_DETAILS: 'MATCH_DETAILS',

  //LeaderBoard
  LEAD_PLAYER: 'LEAD_PLAYER',
  LEAD_TEAM: 'LEAD_TEAM',
  RESET_LEADERBOARD: 'RESET_LEADERBOARD',
  RESET_LEADERBOARD_TEAM: 'RESET_LEADERBOARD_TEAM',
};

export default ActionTypes;
